export const MTM_CANVAS_CSS = [
  ":root { --mtm-bg: #f8fafc; --mtm-fg: #172033; --mtm-muted: #64748b; --mtm-border: #dbe3ee; --mtm-accent: #2563eb; --mtm-card: #ffffff; }",
  ".mtmcanvas-view { display: flex; min-height: 520px; height: 100%; flex-direction: column; overflow: hidden; background: var(--mtm-bg); color: var(--mtm-fg); font-family: ui-sans-serif, system-ui, sans-serif; }",
  ".mtmcanvas-header { display: flex; min-height: 54px; align-items: center; justify-content: space-between; gap: 12px; border-bottom: 1px solid var(--mtm-border); padding: 0 16px; background: var(--mtm-card); }",
  ".mtmcanvas-title { display: flex; min-width: 0; align-items: center; gap: 10px; }",
  ".mtmcanvas-mark { display: grid; width: 30px; height: 30px; place-items: center; border-radius: 8px; background: var(--mtm-accent); color: white; font-size: 16px; font-weight: 700; }",
  ".mtmcanvas-title h2 { margin: 0; overflow: hidden; font-size: 14px; font-weight: 700; text-overflow: ellipsis; white-space: nowrap; }",
  ".mtmcanvas-title p { margin: 2px 0 0; color: var(--mtm-muted); font-size: 11px; }",
  ".mtmcanvas-revision { flex: none; color: var(--mtm-muted); font-family: ui-monospace, monospace; font-size: 11px; }",
  ".mtmcanvas-content { display: grid; min-height: 0; flex: 1; grid-template-columns: minmax(0, 1fr) 280px; }",
  ".mtmcanvas-stage-column { display: flex; min-width: 0; min-height: 0; flex-direction: column; }",
  ".mtmcanvas-toolbar { display: flex; min-height: 46px; align-items: center; justify-content: space-between; gap: 8px; border-bottom: 1px solid var(--mtm-border); padding: 0 12px; }",
  ".mtmcanvas-toolbar small { color: var(--mtm-muted); font-size: 11px; }",
  ".mtmcanvas-button { display: inline-flex; min-height: 30px; align-items: center; justify-content: center; gap: 6px; border: 1px solid var(--mtm-border); border-radius: 6px; padding: 0 10px; background: var(--mtm-card); color: var(--mtm-fg); cursor: pointer; font: inherit; font-size: 11px; font-weight: 650; }",
  ".mtmcanvas-button:hover:not(:disabled) { border-color: var(--mtm-accent); background: #eff6ff; }",
  ".mtmcanvas-button:disabled { cursor: not-allowed; opacity: .5; }",
  ".mtmcanvas-button-primary { border-color: var(--mtm-accent); background: var(--mtm-accent); color: white; }",
  ".mtmcanvas-button-icon { width: 28px; padding: 0; font-size: 16px; }",
  ".mtmcanvas-button:focus-visible, .mtmcanvas-node:focus-visible, .mtmcanvas-node-list-item:focus-visible { outline: 2px solid var(--mtm-accent); outline-offset: 2px; }",
  ".mtmcanvas-stage { position: relative; min-height: 300px; flex: 1; overflow: hidden; touch-action: none; background-color: #f8fbff; background-image: linear-gradient(#dbe7f3 1px, transparent 1px), linear-gradient(90deg, #dbe7f3 1px, transparent 1px); background-size: 28px 28px; color: #64748b; cursor: grab; }",
  ".mtmcanvas-stage:active { cursor: grabbing; }",
  ".mtmcanvas-world { position: absolute; inset: 0; transform-origin: 0 0; }",
  ".mtmcanvas-connections { position: absolute; inset: 0; width: 100%; height: 100%; overflow: visible; pointer-events: none; }",
  ".mtmcanvas-stage-controls { position: absolute; right: 12px; bottom: 12px; display: inline-flex; align-items: center; gap: 3px; border: 1px solid var(--mtm-border); border-radius: 6px; padding: 3px; background: rgba(255,255,255,.94); color: var(--mtm-muted); font-size: 11px; }",
  ".mtmcanvas-stage-controls span { min-width: 35px; text-align: center; }",
  ".mtmcanvas-stage-hint { position: absolute; left: 12px; bottom: 14px; color: var(--mtm-muted); font-size: 11px; pointer-events: none; }",
  ".mtmcanvas-node { position: absolute; z-index: 1; overflow: hidden; border: 1px solid #cbd5e1; border-radius: 8px; background: var(--mtm-card); box-shadow: 0 8px 22px rgba(30, 64, 90, .12); color: var(--mtm-fg); cursor: grab; user-select: none; }",
  ".mtmcanvas-node:hover, .mtmcanvas-node-selected { border-color: var(--mtm-accent); box-shadow: 0 0 0 2px rgba(37,99,235,.16), 0 10px 24px rgba(30,64,90,.16); }",
  ".mtmcanvas-node-header { display: flex; min-height: 40px; align-items: center; justify-content: space-between; gap: 8px; border-bottom: 1px solid var(--mtm-border); padding: 0 10px; }",
  ".mtmcanvas-node-name { overflow: hidden; font-size: 12px; font-weight: 700; text-overflow: ellipsis; white-space: nowrap; }",
  ".mtmcanvas-node-status { color: var(--mtm-muted); font-size: 10px; text-transform: uppercase; }",
  ".mtmcanvas-node-status-ready { color: #047857; }",
  ".mtmcanvas-node-status-live { color: #b45309; }",
  ".mtmcanvas-node-status-failed { color: #b91c1c; }",
  ".mtmcanvas-node-prompt { display: -webkit-box; min-height: 76px; overflow: hidden; margin: 0; padding: 12px; color: var(--mtm-muted); font-size: 12px; line-height: 1.55; -webkit-box-orient: vertical; -webkit-line-clamp: 4; }",
  ".mtmcanvas-preview { position: relative; display: flex; min-height: 150px; align-items: flex-end; overflow: hidden; margin: 9px; border-radius: 6px; background: #dbeafe; color: #1e3a8a; }",
  ".mtmcanvas-preview-sun { position: absolute; top: 20px; right: 25px; width: 34px; height: 34px; border-radius: 50%; background: #fbbf24; }",
  ".mtmcanvas-preview-subject { position: absolute; left: 50%; bottom: 24px; width: 70px; height: 96px; transform: translateX(-50%); border-radius: 35px 35px 15px 15px; background: #1e3a8a; box-shadow: 0 -22px 0 -7px #b7795d; }",
  ".mtmcanvas-preview-ground { position: absolute; right: -20%; bottom: -35px; left: -20%; height: 78px; border-radius: 50% 50% 0 0; background: #93c5fd; }",
  ".mtmcanvas-preview-label { position: relative; z-index: 2; margin: 0 8px 7px; padding: 3px 5px; border-radius: 4px; background: rgba(255,255,255,.78); font-size: 10px; font-weight: 700; }",
  ".mtmcanvas-empty-preview { display: grid; min-height: 150px; place-items: center; margin: 9px; border: 1px dashed #cbd5e1; border-radius: 6px; color: var(--mtm-muted); font-size: 11px; }",
  ".mtmcanvas-inspector { display: flex; min-width: 0; min-height: 0; flex-direction: column; gap: 10px; overflow-y: auto; border-left: 1px solid var(--mtm-border); padding: 14px; background: var(--mtm-card); }",
  ".mtmcanvas-inspector h3 { margin: 0; font-size: 12px; }",
  ".mtmcanvas-copy { margin: 0; color: var(--mtm-muted); font-size: 11px; line-height: 1.5; }",
  ".mtmcanvas-textarea { width: 100%; resize: vertical; border: 1px solid var(--mtm-border); border-radius: 6px; padding: 8px; background: var(--mtm-bg); color: var(--mtm-fg); font: inherit; font-size: 12px; line-height: 1.5; }",
  ".mtmcanvas-textarea:focus { border-color: var(--mtm-accent); outline: 2px solid rgba(37,99,235,.16); }",
  ".mtmcanvas-status { display: flex; min-width: 0; align-items: center; gap: 6px; color: var(--mtm-muted); font-size: 11px; }",
  ".mtmcanvas-status-dot { width: 7px; height: 7px; flex: none; border-radius: 50%; background: #059669; }",
  ".mtmcanvas-status-dot-live { background: #f59e0b; }",
  ".mtmcanvas-status-dot-error { background: #dc2626; }",
  ".mtmcanvas-error { border: 1px solid #fecaca; border-radius: 6px; padding: 7px; color: #b91c1c; font-size: 11px; line-height: 1.45; }",
  ".mtmcanvas-rule { height: 1px; background: var(--mtm-border); }",
  ".mtmcanvas-list-title { display: flex; justify-content: space-between; color: var(--mtm-muted); font-size: 10px; font-weight: 700; letter-spacing: .04em; text-transform: uppercase; }",
  ".mtmcanvas-node-list { display: flex; flex-direction: column; gap: 4px; }",
  ".mtmcanvas-node-list-item { display: flex; min-width: 0; align-items: center; gap: 7px; border: 1px solid transparent; border-radius: 5px; padding: 7px; background: transparent; color: var(--mtm-fg); cursor: pointer; font: inherit; text-align: left; }",
  ".mtmcanvas-node-list-item:hover, .mtmcanvas-node-list-item-selected { border-color: var(--mtm-border); background: #eff6ff; }",
  ".mtmcanvas-node-list-item strong { overflow: hidden; flex: 1; font-size: 11px; text-overflow: ellipsis; white-space: nowrap; }",
  ".mtmcanvas-node-list-item small { color: var(--mtm-muted); font-size: 10px; }",
  "@media (max-width: 760px) { .mtmcanvas-content { grid-template-columns: minmax(0, 1fr); grid-template-rows: minmax(300px, 1fr) auto; } .mtmcanvas-inspector { max-height: 42%; border-top: 1px solid var(--mtm-border); border-left: 0; } .mtmcanvas-stage-hint { display: none; } }",
].join("\n");
